app_core/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path, re_path
from django.utils.translation import gettext_lazy as _
from drf_yasg import openapi
from drf_yasg.views import get_schema_view
from two_factor.urls import urlpatterns as tf_urls

from apps.common.utils.views import handler400 as h400
from apps.common.utils.views import handler403 as h403
from apps.common.utils.views import handler404 as h404
from apps.common.utils.views import handler500 as h500

admin_url = settings.ADMIN_URL
custom_apps = settings.ALL_CUSTOM_APPS
utils_path = settings.UTILS_PATH

apps_urls = [path('', include(f'{app}.urls')) for app in custom_apps]

handler400 = h400

handler403 = h403

handler404 = h404

handler500 = h500

third_party_urls = [
    re_path(
        r'^rosetta/',
        include('rosetta.urls')
    ),
]

admin_urls = [
    path(admin_url, admin.site.urls),
]

two_factor_urls = [
    path('', include(tf_urls)),
]

rest_urls = [
    path(
        'api-auth/',
        include('rest_framework.urls')
    )
]

schema_view = get_schema_view(
    openapi.Info(
        title='Backend Endpoints',
        default_version='v1.0.0',
        description=_('API documentation and endpoint representation'),
        terms_of_service='',
        contact=openapi.Contact(email=settings.YASG_DEFAULT_EMAIL),
        license=openapi.License(name=settings.YASG_TERMS_OF_SERVICE),
    ),
    public=False,
)

swagger_urls = [
    re_path(
        r'^api/docs/',
        schema_view.with_ui(
            'swagger',
            cache_timeout=0
        ),
        name='schema-swagger-ui'
    ),
    re_path(
        r'^api/redocs/',
        schema_view.with_ui(
            'redoc',
            cache_timeout=0
        ),
        name='schema-redoc'
    ),
    re_path(
        r'^api/docs/<format>/',
        schema_view.without_ui(
            cache_timeout=0
        ),
        name='schema-json-yaml'
    ),
]

ckeditor_urls = [
    path(
        "ckeditor5/",
        include('django_ckeditor_5.urls')
    ),
]

django_select2_urls = [
    path(
        'select2/',
        include('django_select2.urls')
    )
]

urlpatterns = admin_urls + two_factor_urls + \
    apps_urls + third_party_urls + swagger_urls + ckeditor_urls + django_select2_urls

if settings.DEBUG:
    urlpatterns += static(
        settings.STATIC_URL,
        document_root=settings.STATIC_ROOT
    )
    urlpatterns += static(
        settings.MEDIA_URL,
        document_root=settings.MEDIA_ROOT
    )

apps/common/core/urls.py
from django.urls import include, path

from apps.common.core.views import IndexTemplateView

app_name = 'core'

urlpatterns = [
    path(
        '',
        IndexTemplateView.as_view(),
        name='index'
    )
]

apps/project/specific/assets_management/assets_location/urls.py
from django.urls import path

from .views import (AseetLocationDeleteView, AssetLocationCreateView,
                    AssetUpdateView, LocationCreateView,
                    LocationReferenceDeleteView, LocationUpdateView)

app_name = 'assets_location'

urlpatterns = [
    path(
        'asset/add/location/',
        LocationCreateView.as_view(),
        name='add_location'
    ),
    path(
        'asset/delete/location/<uuid:pk>/',
        LocationReferenceDeleteView.as_view(),
        name='delete_location'
    ),
    path(
        'asset/update/location/<uuid:pk>/',
        LocationUpdateView.as_view(),
        name='update_location'
    ),

    path(
        'asset/add/',
        AssetLocationCreateView.as_view(),
        name='add_asset_location'
    ),
    path(
        'asset/delete/<uuid:pk>/',
        AseetLocationDeleteView.as_view(),
        name='delete_asset_location'
    ),
    path(
        'asset/update/<uuid:pk>/',
        AssetUpdateView.as_view(),
        name='update_asset_location'
    ),
]

templates/dashboard/partials/account_footer.html
{% load i18n %}
<footer class="footer-admin mt-auto footer-dark">
    <div class="container-xl px-4">
        <div class="row">
            <div class="col-md-6 small">© {% now "M Y" %}
                <a class="px-1 sitename" href="https://propensionesabogados.com" target="_blank">
                    Propensiones Abogados.
                </a>
                {% trans 'Your unconditional ally. All Rights Reserved.' %}
            </div>
            <div class="col-md-6 text-md-end small">
                Made by
                <a href="http://sebasmoralesd.com" target="_blank">
                    Sebastian Morales
                </a>
                &middot;
                <!-- TODO TYC footer -->
                <!-- <a href="#!">{% trans "Terms & Conditions" %}</a> -->
            </div>
        </div>
    </div>
</footer>

templates/dashboard/partials/footer.html
{% load i18n %}

<footer class="footer-admin mt-auto footer-light">
    <div class="container-xl px-4">
        <div class="row">
            <div class="col-md-6 small">
                &copy; {% now "M Y" %} <a class="px-1 sitename" href="https://propensionesabogados.com" target="_blank">
                    Propensiones Abogados.
                </a>{% trans 'Your unconditional ally. All Rights Reserved.' %} {% trans 'Created by' %} 
                <a href="http://sebasmoralesd.com" target="_blank">
                    Sebastian Morales
                </a>
            </div>
            <div class="col-md-6 text-md-end small">
                <!-- TODO TYC -->
                <!-- <a href="#!">Privacy Policy</a>
                &middot;
                <a href="#!">Terms &amp; Conditions</a> -->
            </div>
        </div>
    </div>
</footer>

templates/dashboard/partials/nav.html
{% load i18n static %}
<nav class="topnav navbar navbar-expand shadow justify-content-between justify-content-sm-start navbar-light bg-white" id="sidenavAccordion">
    <button class="btn btn-icon btn-transparent-dark order-1 order-lg-0 me-2 ms-lg-2 me-lg-0" id="sidebarToggle"><i data-feather="menu"></i></button>
    <a class="navbar-brand pe-3 ps-4 ps-lg-2" href="{% url 'core:index' %}">
        <img src="{% static 'assets/imgs/horizontal-logo.png' %}" alt="" style="height:50px">
    </a>
    
    <ul class="navbar-nav align-items-center ms-auto">

        {% comment %}
            {% include 'dashboard/partials/nav/documentation.html' %}
        {% endcomment %}

        {% comment %}
            {% include 'dashboard/partials/nav/alerts.html' %}
        {% endcomment %}

        {% comment %}
            {% include 'dashboard/partials/nav/messages.html' %}
        {% endcomment %}

        {% include 'dashboard/partials/nav/user.html' %}
        
    </ul>

</nav>

templates/dashboard/partials/side_nav.html
{% load i18n %}

<nav class="sidenav shadow-right sidenav-light">
    <div class="sidenav-menu">
        <div class="nav accordion" id="accordionSidenav">
            {% comment %}
                <div class="sidenav-menu-heading d-sm-none">Account</div>
                <a class="nav-link d-sm-none" href="#!">
                    <div class="nav-link-icon"><i data-feather="bell"></i></div>
                    Alerts
                    <span class="badge bg-warning-soft text-warning ms-auto">4 New!</span>
                </a>
                <a class="nav-link d-sm-none" href="#!">
                    <div class="nav-link-icon"><i data-feather="mail"></i></div>
                    Messages
                    <span class="badge bg-success-soft text-success ms-auto">2 New!</span>
                </a>
            {% endcomment %}

            

            <div class="sidenav-menu-heading">{% trans 'Dashboard' %}</div>

            <a class="nav-link collapsed" href="javascript:void(0);" data-bs-toggle="collapse" data-bs-target="#collapseLanguage" aria-expanded="false" aria-controls="collapseLanguage">
                <div class="nav-link-icon"><i data-feather="globe"></i></div>
                {% trans 'Language' %}
                <div class="sidenav-collapse-arrow"><i class="fas fa-angle-down"></i></div>
            </a>
            <div class="collapse" id="collapseLanguage" data-bs-parent="#accordionSidenav">
                <nav class="sidenav-menu-nested nav">
                    {% for lang in LANGUAGES %}
                        <a class="nav-link text-capitalize" href="{% url 'set_language' %}?lang={{ lang.0 }}">{{ lang.1 }}</a>
                    {% endfor %}
                </nav>
            </div>

            <a class="nav-link collapsed" href="javascript:void(0);" data-bs-toggle="collapse" data-bs-target="#collapsePages" aria-expanded="false" aria-controls="collapsePages">
                <div class="nav-link-icon"><i data-feather="grid"></i></div>
                {% trans 'Pages' %}
                <div class="sidenav-collapse-arrow"><i class="fas fa-angle-down"></i></div>
            </a>
            <div class="collapse" id="collapsePages" data-bs-parent="#accordionSidenav">
                <nav class="sidenav-menu-nested nav accordion" id="accordionSidenavPagesMenu">
                    <a class="nav-link collapsed" href="javascript:void(0);" data-bs-toggle="collapse" data-bs-target="#pagesCollapseAccount" aria-expanded="false" aria-controls="pagesCollapseAccount">
                        {% trans 'Account' %}
                        <div class="sidenav-collapse-arrow"><i class="fas fa-angle-down"></i></div>
                    </a>
                    <div class="collapse" id="pagesCollapseAccount" data-bs-parent="#accordionSidenavPagesMenu">
                        <nav class="sidenav-menu-nested nav">
                            <!-- <a class="nav-link" href="account-profile.html">Profile</a> -->
                            <a class="nav-link" href="{% url 'two_factor:profile' %}">{% trans 'Security' %}</a>
                            <!-- <a class="nav-link" href="account-notifications.html">Notifications</a> -->
                        </nav>
                    </div>
                </nav>
            </div>

            <a class="nav-link collapsed" href="javascript:void(0);" data-bs-toggle="collapse" data-bs-target="#collapseApps" aria-expanded="false" aria-controls="collapseApps">
                <div class="nav-link-icon"><i data-feather="globe"></i></div>
                {% trans 'Documents' %}
                <div class="sidenav-collapse-arrow"><i class="fas fa-angle-down"></i></div>
            </a>
            <div class="collapse" id="collapseApps" data-bs-parent="#accordionSidenav">
                <nav class="sidenav-menu-nested nav accordion" id="accordionSidenavAppsMenu">
                    <a class="nav-link" href="https://wa.me/573183280176?text=KYC" target="_blank" rel="noopener noreferrer">KYC</a>
                    <a class="nav-link" href="https://wa.me/573183280176?text=CIS" target="_blank" rel="noopener noreferrer">CIS</a>
                    <a class="nav-link" href="https://wa.me/573183280176?text=IDONEIDAD" target="_blank" rel="noopener noreferrer">{% trans 'IDONEITY' %}</a>
                </nav>
            </div>

            {% if request.user.user_type in 'HRI' %}
                {% if request.user.is_verified_holder %}
                <a class="nav-link collapsed" href="javascript:void(0);" data-bs-toggle="collapse" data-bs-target="#collapseAssets" aria-expanded="false" aria-controls="collapseAssets">
                    <div class="nav-link-icon"><i data-feather="box"></i></div>
                    {% trans 'Assets' %}
                    <div class="sidenav-collapse-arrow"><i class="fas fa-angle-down"></i></div>
                </a>
                <div class="collapse" id="collapseAssets" data-bs-parent="#accordionSidenav">
                    <nav class="sidenav-menu-nested nav">
                        <a class="nav-link" href="{% url 'assets_location:add_location' %}">{% trans 'Add Location Reference' %}</a>
                        <a class="nav-link" href="{% url 'assets_location:add_asset_location' %}">{% trans 'Add Asset' %}</a>
                    </nav>
                </div>
                {% endif %}
            {% endif %}
        </div>
    </div>
    {% include 'dashboard/partials/side_nav/footer.html' %}
</nav>