app_core/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path, re_path
from django.utils.translation import gettext_lazy as _
from drf_yasg import openapi
from drf_yasg.views import get_schema_view
from two_factor.urls import urlpatterns as tf_urls

from apps.common.utils.views import handler400 as h400
from apps.common.utils.views import handler403 as h403
from apps.common.utils.views import handler404 as h404
from apps.common.utils.views import handler500 as h500

admin_url = settings.ADMIN_URL
custom_apps = settings.ALL_CUSTOM_APPS
utils_path = settings.UTILS_PATH

apps_urls = [path('', include(f'{app}.urls')) for app in custom_apps]

handler400 = h400

handler403 = h403

handler404 = h404

handler500 = h500

third_party_urls = [
    re_path(
        r'^rosetta/',
        include('rosetta.urls')
    ),
]

admin_urls = [
    path(admin_url, admin.site.urls),
]

two_factor_urls = [
    path('', include(tf_urls)),
]

rest_urls = [
    path(
        'api-auth/',
        include('rest_framework.urls')
    )
]

schema_view = get_schema_view(
    openapi.Info(
        title='Backend Endpoints',
        default_version='v1.0.0',
        description=_('API documentation and endpoint representation'),
        terms_of_service='',
        contact=openapi.Contact(email=settings.YASG_DEFAULT_EMAIL),
        license=openapi.License(name=settings.YASG_TERMS_OF_SERVICE),
    ),
    public=False,
)

swagger_urls = [
    re_path(
        r'^api/docs/',
        schema_view.with_ui(
            'swagger',
            cache_timeout=0
        ),
        name='schema-swagger-ui'
    ),
    re_path(
        r'^api/redocs/',
        schema_view.with_ui(
            'redoc',
            cache_timeout=0
        ),
        name='schema-redoc'
    ),
    re_path(
        r'^api/docs/<format>/',
        schema_view.without_ui(
            cache_timeout=0
        ),
        name='schema-json-yaml'
    ),
]

ckeditor_urls = [
    path(
        "ckeditor5/",
        include('django_ckeditor_5.urls')
    ),
]

django_select2_urls = [
    path(
        'select2/',
        include('django_select2.urls')
    )
]

urlpatterns = admin_urls + two_factor_urls + \
    apps_urls + third_party_urls + swagger_urls + ckeditor_urls + django_select2_urls

if settings.DEBUG:
    urlpatterns += static(
        settings.STATIC_URL,
        document_root=settings.STATIC_ROOT
    )
    urlpatterns += static(
        settings.MEDIA_URL,
        document_root=settings.MEDIA_ROOT
    )

apps/common/core/urls.py
from django.urls import include, path

from apps.common.core.views import IndexTemplateView

app_name = 'core'

urlpatterns = [
    path(
        '',
        IndexTemplateView.as_view(),
        name='index'
    )
]

apps/project/common/account/urls.py
from django.urls import path

from .views import (AtlasUserRegisterView, PropensionesUserRegisterView,
                    UserLogoutView, UserPreregisterView)

app_name = "account"

urlpatterns = [
    path(
        'account/register/',
        UserPreregisterView.as_view(),
        name='register'
    ),
    path(
        'account/register/atlas/',
        AtlasUserRegisterView.as_view(),
        name='register-atlas'
    ),
    path(
        'account/register/propensiones/',
        PropensionesUserRegisterView.as_view(),
        name='register-propensiones'
    ),
    path(
        'account/logout/',
        UserLogoutView.as_view(),
        name='logout'
    )
]

apps/project/specific/assets_management/assets/urls.py
from django.urls import path

from .views import (
    HolderTemplateview,
)

app_name = 'assets'

urlpatterns = [
    path(
        'asset/holder/',
        HolderTemplateview.as_view(),
        name='holder_index'
    ),
]

apps/project/specific/documents/certificates/urls.py
from django.urls import path

from .views import LockoutTimeView, CertificateInputView, CertificateDetailView, SovereignPurchaseCertificateDetailView, SovereignPurchaseCertificateInputView

app_name = 'certificates'

urlpatterns = [

    path(
        'lockout-time/',
        LockoutTimeView.as_view(),
        name='lockout_time'
    ),



    path(
        'certificate/',
        CertificateInputView.as_view(),
        name='input'
    ),
    path(
        'certificate/<uuid:pk>/',
        CertificateDetailView.as_view(),
        name='detail'
    ),



    path(
        'certificate/sovereign/',
        SovereignPurchaseCertificateInputView.as_view(),
        name='sovereign_input'
    ),
    path(
        'certificate/sovereign/<uuid:pk>/',
        SovereignPurchaseCertificateDetailView.as_view(),
        name='sovereign_detail'
    ),
]

apps/project/specific/internal/code_gen/urls.py
from django.urls import path

from .views import CodeGeneratorView, dynamic_qr_view

app_name = "code_gen"

urlpatterns = [
    path(
        "generate/code/",
        CodeGeneratorView.as_view(),
        name="code_generate"
    ),
    path(
        "qr/generate/<path:text>/",
        dynamic_qr_view,
        name="dynamic_qr"
    ),
]

apps/common/core/models.py
import uuid

from django.db import models
from django.utils.translation import gettext_lazy as _

from apps.common.utils.models import TimeStampedModel


class ContactModel(TimeStampedModel):
    unique_id = models.UUIDField(
        default=uuid.uuid4,
        unique=True
    )

    name = models.CharField(
        _('name'),
        max_length=255
    )

    last_name = models.CharField(
        _('last name'),
        max_length=255
    )

    email = models.EmailField(
        _('email'),
        max_length=255,
    )

    subject = models.CharField(
        _('subject'),
        max_length=255
    )

    message = models.TextField(
        _('message'),
    )

    class Meta:
        db_table = 'apps_core_contact'
        verbose_name = _('Contact')
        verbose_name_plural = _('Contacts')

    def __str__(self):
        return self.name

class ModalBannerModel(TimeStampedModel):
    title = models.CharField(
        _('title'),
        max_length=255
    )
    
    title_en = models.CharField(
        _('title (English)'),
        max_length=255,
        blank=True,
        null=True
    )

    description = models.TextField(
        _('description'),
        blank=True, null=True
    )

    image_file = models.ImageField(
        _('image file'),
        upload_to='modal_banners/'
    )
    
    image_file_en = models.ImageField(
        _('image file (English)'),
        upload_to='modal_banners/',
        blank=True,
        null=True
    )
    
    link = models.URLField(
        _('link'),
        max_length=255,
        blank=True,
        null=True
    )
    
    link_en = models.URLField(
        _('link (English)'),
        max_length=255,
        blank=True,
        null=True
    )

    def save(self, *args, **kwargs):
        if self.is_active:
            ModalBannerModel.objects.filter(
                is_active=True
            ).update(
                is_active=False
            )
        super().save(*args, **kwargs)

    class Meta:
        db_table = 'apps_common_core_modal_banner'
        verbose_name = _('Modal Banner')
        verbose_name_plural = _('Modal Banners')
        ordering = ['-created']

    def __str__(self):
        return self.title

apps/common/core/forms.py
import uuid

from django import forms
from django.utils.translation import gettext_lazy as _
from django_recaptcha.fields import ReCaptchaField

from apps.common.core.models import ContactModel
from apps.project.common.users.validators import (UnicodeLastNameValidator,
                                                  UnicodeNameValidator)


class ContactForm(forms.ModelForm):
    FIRST_NAME_TXT = _('First name')
    LAST_NAME_TXT = _('Last name')
    EMAIL_TXT = _('Your Email')
    SUBJECT_TXT = _('Subject')
    MESSAGE_TXT = _('Message')
    UNIQUE_ID_INITIAL_VALUE = uuid.uuid4()
    
    last_name_validator = UnicodeLastNameValidator()
    name_validator = UnicodeNameValidator()

    name = forms.CharField(
        label=FIRST_NAME_TXT,
        required=True,
        validators=[name_validator],
        widget=forms.TextInput(
            attrs={
                "id": "contact_first_name",
                "name": "contact_first_name",
                "type": "text",
                "placeholder": FIRST_NAME_TXT,
                "class": "form-control",
                'aria-label': FIRST_NAME_TXT,
                'aria-describedby': 'contact_first_name'
            }
        )
    )

    last_name = forms.CharField(
        label=LAST_NAME_TXT,
        required=True,
        validators=[last_name_validator],
        widget=forms.TextInput(
            attrs={
                "id": "contact_last_name",
                "name": "contact_last_name",
                "type": "text",
                "placeholder": LAST_NAME_TXT,
                "class": "form-control",
                'aria-label': LAST_NAME_TXT,
                'aria-describedby': 'contact_last_name'
            }
        )
    )

    subject = forms.CharField(
        label=SUBJECT_TXT,
        required=True,
        widget=forms.TextInput(
            attrs={
                "id": "contact_subject",
                "name": "contact_subject",
                "type": "text",
                "placeholder": SUBJECT_TXT,
                "class": "form-control",
                'aria-label': SUBJECT_TXT,
                'aria-describedby': 'contact_subject'
            }
        )
    )

    email = forms.CharField(
        label=EMAIL_TXT,
        required=True,
        widget=forms.EmailInput(
            attrs={
                "id": "contact_email",
                "name": "contact_email",
                "type": "email",
                "placeholder": EMAIL_TXT,
                "class": "form-control",
                'aria-label': EMAIL_TXT,
                'aria-describedby': 'contact_email'
            }
        )
    )

    message = forms.CharField(
        label=MESSAGE_TXT,
        required=True,
        widget=forms.Textarea(
            attrs={
                "id": "contact_message",
                "name": "contact_message",
                "placeholder": MESSAGE_TXT,
                "class": "form-control",
                'aria-label': MESSAGE_TXT,
                'aria-describedby': 'contact_message',
                'rows': 2
            }
        )
    )

    unique_id = forms.UUIDField(
        widget=forms.HiddenInput(
            attrs={
                "id": "unique_id",
                "name": "unique_id",
                "type": "hidden",
                "value": UNIQUE_ID_INITIAL_VALUE
            }
        ),
        initial=UNIQUE_ID_INITIAL_VALUE,
    )

    captcha = ReCaptchaField(
        required=True,
        label=''
    )

    class Meta:
        model = ContactModel
        fields = '__all__'

apps/common/core/views.py
import logging

from django.conf import settings
from django.core.mail import send_mail
from django.shortcuts import render
from django.template.loader import render_to_string
from django.urls import reverse_lazy
from django.utils.decorators import method_decorator
from django.utils.translation import gettext_lazy as _
from django.views.generic.edit import FormView
from honeypot.decorators import check_honeypot

from .forms import ContactForm
from .models import ContactModel, ModalBannerModel

logger = logging.getLogger(__name__)


@method_decorator(check_honeypot, name='post')
class IndexTemplateView(FormView):
    template_name = "core/index/index.html"
    form_class = ContactForm
    success_url = reverse_lazy('core:index')

    def form_valid(self, form):
        unique_id = form.cleaned_data.get('unique_id')
        honeypot_field = form.cleaned_data.get('email_confirm')

        if ContactModel.objects.filter(unique_id=unique_id).exists():
            form.add_error(None, _("This form has already been sent."))
            return self.form_invalid(form)

        if honeypot_field:
            form.save()
            return render(self.request, self.template_name, {'form': None, 'success_message': True})

        contact = form.save()

        user_language = self.request.LANGUAGE_CODE

        html_message = render_to_string('core/email/contact_email_template.html', {
            'names': contact.name,
            'LANGUAGE_CODE': user_language,
        })

        subject = _('Message Received! | ATLAS')

        plain_message = _('Thank you %(name)s for contacting us.') % {
            'name': contact.name}

        try:
            send_mail(
                subject=subject,
                message=plain_message,
                html_message=html_message,
                from_email=settings.DEFAULT_FROM_EMAIL,
                recipient_list=[contact.email],
                fail_silently=False
            )
        except Exception as e:
            logger.error(f"An unexpected error occurred sending mail: {e}")
            return render(self.request, self.template_name, {'form': None, 'success_message': True})

        return render(self.request, self.template_name, {'form': None, 'success_message': True})

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        banner = ModalBannerModel.objects.filter(is_active=True).first()
        context['modal_banner'] = banner
        return context

templates/core/partials/banner.html
{% load i18n %}

{% if modal_banner %}
<div id="modalBanner" class="modal fade vh-100 d-flex align-items-center" data-bs-backdrop="static" data-bs-keyboard="true" tabindex="-1" aria-labelledby="staticBackdropLabel" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered">
        <div class="modal-content">
            <div class="modal-body p-0">
                {% if LANGUAGE_CODE == 'en' %}
                    {% if modal_banner.image_file_en %}
                        <img src="{{ modal_banner.image_file_en.url }}" alt="{{ modal_banner.title_en }}" class="img-fluid vh-90">
                    {% else %}
                        {% if modal_banner.image_file %}
                            <img src="{{ modal_banner.image_file.url }}" alt="{{ modal_banner.title }}" class="img-fluid">
                        {% endif %}
                    {% endif %}
                {% else %}
                    {% if modal_banner.image_file %}
                        <img src="{{ modal_banner.image_file.url }}" alt="{{ modal_banner.title }}" class="img-fluid">
                    {% endif %}
                {% endif %}
                {% if LANGUAGE_CODE == 'en' and modal_banner.link_en %}
                    <a href="{{ modal_banner.link_en }}" target="_blank" class="stretched-link"></a>
                {% elif modal_banner.link %}
                    <a href="{{ modal_banner.link }}" target="_blank" class="stretched-link"></a>
                {% endif %}
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-outline-danger" data-bs-dismiss="modal">{% trans 'Close' %}</button>
                {% if LANGUAGE_CODE == 'en' and modal_banner.link_en %}
                    <a href="{{ modal_banner.link_en }}" target="_blank" class="btn btn-outline-success">{% trans 'View more' %}</a>
                {% elif modal_banner.link %}
                    <a href="{{ modal_banner.link }}" target="_blank" class="btn btn-outline-success">{% trans 'View more' %}</a>
                {% endif %}
            </div>
        </div>
    </div>
</div>

<script>
    document.addEventListener('DOMContentLoaded', function () {
        var modalBanner = new bootstrap.Modal(document.getElementById('modalBanner'));
        setTimeout(function () {
            modalBanner.show();
        }, 500);
    
        document.getElementById('modalBanner').addEventListener('hidden.bs.modal', function () {
            document.getElementById('modalBanner').remove();
        });
    });
</script>
{% endif %}

templates/core/partials/footer.html
{% load i18n %}

<footer id="footer" class="footer mt-3">
    <div class="container footer-top">
        <div class="row gy-4 justify-content-evenly">

          <div class="col-md-3 footer-about">
            <a href="{% url 'core:index' %}" class="logo d-flex align-items-center">
              <span class="sitename">ATLAS</span>
            </a>
            <div class="footer-contact pt-3">
              <p>Calle 21 No. 16-37 Oficina 705 Edificio BancoPopular</p>
              <p>Colombia, Armenia, Quindio</p>
              <p class="mt-3"><strong>{% trans 'Phone:' %}</strong> <span>+(57) 318 328 01 76</span></p>
              <p><strong>{% trans 'Email:' %}</strong> <span>support@propensionesabogados.com</span></p>
            </div>
          </div>
  
          <div class="col-md-3 footer-links">
            <h4>{% trans 'Useful Links' %}</h4>
            <ul>
              <li><a href="{% url 'core:index' %}#hero">{% trans 'Home' %}</a></li>
              <li><a href="{% url 'core:index' %}#about">{% trans 'About us' %}</a></li>
              <li><a href="{% url 'core:index' %}">{% trans 'Terms of service' %}</a></li>
              <li><a href="{% url 'core:index' %}">{% trans 'Privacy policy' %}</a></li>
            </ul>
          </div>
  
          {% comment %}
          <div class="col-md-3 footer-links">
            <h4>{% trans 'Our Services' %}</h4>
            <ul>
              <li><a href="{% url 'core:index' %}">S1</a></li>
              <li><a href="{% url 'core:index' %}">S2</a></li>
              <li><a href="{% url 'core:index' %}">S3</a></li>
              <li><a href="{% url 'core:index' %}">S4</a></li>
              <li><a href="{% url 'core:index' %}">S5</a></li>
            </ul>
          </div>
          {% endcomment %}
    
          
          {% comment %}
          <div class="col-md-3 footer-links">
            <h4>{% trans 'Social Networks' %}</h4>
            <div class="social-links d-flex mt-4">
              <a href=""><i class="bi bi-twitter-x"></i></a>
              <a href=""><i class="bi bi-facebook"></i></a>
              <a href=""><i class="bi bi-instagram"></i></a>
              <a href=""><i class="bi bi-linkedin"></i></a>
            </div>
          </div>
          {% endcomment %}

        </div>
      </div>
  
    <div class="container copyright text-center mt-4">
        <p>&copy; {% now "M Y" %} <a class="px-1 sitename" href="https://propensionesabogados.com" target="_blank">Propensiones Abogados.</a>{% trans 'Your unconditional ally. All Rights Reserved.' %} </p>
        <div class="credits">
            {% trans 'Created by' %} <a href="http://sebasmoralesd.com" target="_blank">Sebastian Morales</a>
        </div>
    </div>
</footer>

templates/core/partials/header.html
{% load static i18n %}

<header id="header" class="header d-flex align-items-center fixed-top">
  <div class="header-container container-fluid container-xl position-relative d-flex align-items-center justify-content-between">
    <a href="{% url 'core:index' %}" class="logo d-flex align-items-center me-auto me-xl-0"><img src="{% static 'assets/imgs/horizontal-logo.png' %}" alt="ATLAS horizontal logo" /></a>

    <nav id="navmenu" class="navmenu">
      <ul>
        <li>
          <a href="{% url 'core:index' %}#hero" class="active">{% trans 'Home' %}</a>
        </li>

        
        
          
        <li class="dropdown">
          <a href="#">{% trans 'About' %} <i class="bi bi-chevron-down toggle-dropdown"></i></a>
          <ul>
            <li><a href="{% url 'core:index' %}#about">{% trans 'About' %}</a></li>
            <li><a href="{% url 'core:index' %}#features">{% trans 'Features' %}</a></li>
            <li><a href="{% url 'core:index' %}#team">{% trans 'Team' %}</a></li>
          </ul>
        </li>

        <li><a href="{% url 'core:index' %}#contact">{% trans 'Contact' %}</a></li>
        
        {% if request.user.is_authenticated and request.user.is_staff %}
          <li class="dropdown">
            <a href="#"><span>{% trans 'Custom APPS' %}</span> <i class="bi bi-chevron-down toggle-dropdown"></i></a>
            <ul>
              <li class="dropdown">
                <a href="{% url 'code_gen:code_generate' %}">{% trans 'Code Generation' %}</a>
              </li>
              {% comment %}
              <li>
                <a href="#">Dropdown 1</a>
              </li>
              {% endcomment %}
            </ul>
          </li>
        {% endif %}

        <li class="dropdown">
          <a href="#"><span>{% trans 'Documents' %}</span> <i class="bi bi-chevron-down toggle-dropdown"></i></a>
          <ul>
            <li>
              <a href="{% url 'certificates:input' %}">{% trans 'Suitability Verification' %}</a>
            </li>
          </ul>
        </li>

        <li class="dropdown">
          <a href="#"><i class="bi bi-translate mx-1"></i> <i class="bi bi-chevron-down toggle-dropdown"></i></a>
          <ul>
            {% for lang in LANGUAGES %}
              <li>
                <a class="dropdown-item text-capitalize" href="{% url 'set_language' %}?lang={{ lang.0 }}">{{ lang.1 }}</a>
              </li>
            {% endfor %}
          </ul>
        </li>
      </ul>
      <i class="mobile-nav-toggle d-xl-none bi bi-list"></i>
    </nav>
    
    {% if request.user.is_authenticated %}
    <div>
      {% if request.user.user_type in 'HRI' or request.user.is_superuser %}
        <a href="{% url 'assets:holder_index' %}" class="btn btn-primary rounded-pill mb-1">{% trans 'Client Area' %}</a>
      {% endif %}

      {% if request.user.user_type in 'B' or request.user.is_superuser %}
        <a href="{% url 'buyers:buyer_index' %}" class="btn btn-primary rounded-pill mb-1">{% trans 'Buyer' %}</a>
      {% endif %}
        
      <a href="{% url 'account:logout' %}" class="btn btn-outline-danger rounded-pill">{% trans 'LOGOUT' %}</a>
    </div>
    {% else %}
    <div>
      <a href="{% url 'two_factor:login' %}" class="btn btn-success rounded-pill mb-1">{% trans 'LOGIN' %}</a>
      <a href="{% url 'account:register' %}" class="btn btn-outline-primary rounded-pill">{% trans 'REGISTER' %}</a>
    </div>
    {% endif %}
  </div>
</header>

templates/core/partials/whatsapp.html
{% load i18n %}
<div class="action-buttons mx-5">
  <div
    class="whatsapp-button"
    data-bs-toggle="modal"
    data-bs-target="#whatsappModal"
  >
    <i class="bi bi-whatsapp"></i>
  </div>
</div>

<div
  class="modal fade modal-whatsapp"
  id="whatsappModal"
  tabindex="-1"
  aria-hidden="true"
>
  <div class="modal-dialog modal-dialog-centered">
    <div class="modal-content">
      <div class="chat-header">
        <span>WhatsApp</span>
        <button
          type="button"
          class="btn-close btn-close-black"
          data-bs-dismiss="modal"
          aria-label="Close"
        ></button>
      </div>
      <div class="chat-body">
        <h5>{% trans 'Ask us your concerns and we can help you.' %}🤝</h5>
        <h6>
          {% trans 'Talk to an adviser now' %}
          <i class="bi bi-chat-left-text-fill"></i>
        </h6>
      </div>
      <div class="chat-footer">
        {% trans 'Write your message...' as message_placeholder %}
        <input
          type="text"
          id="messageInput"
          placeholder="{{message_placeholder}}"
          class="form-control"
        />
        <button id="sendMessage">
          <i class="bi bi-send"></i>
        </button>
      </div>
    </div>
  </div>
</div>