app_core/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path, re_path
from django.utils.translation import gettext_lazy as _
from drf_yasg import openapi
from drf_yasg.views import get_schema_view
from two_factor.urls import urlpatterns as tf_urls

from apps.common.utils.views import handler400 as h400
from apps.common.utils.views import handler403 as h403
from apps.common.utils.views import handler404 as h404
from apps.common.utils.views import handler500 as h500

admin_url = settings.ADMIN_URL
custom_apps = settings.ALL_CUSTOM_APPS
utils_path = settings.UTILS_PATH

apps_urls = [path('', include(f'{app}.urls')) for app in custom_apps]

handler400 = h400

handler403 = h403

handler404 = h404

handler500 = h500

third_party_urls = [
    re_path(
        r'^rosetta/',
        include('rosetta.urls')
    ),
]

admin_urls = [
    path(admin_url, admin.site.urls),
]

two_factor_urls = [
    path('', include(tf_urls)),
]

rest_urls = [
    path(
        'api-auth/',
        include('rest_framework.urls')
    )
]

schema_view = get_schema_view(
    openapi.Info(
        title='Backend Endpoints',
        default_version='v1.0.0',
        description=_('API documentation and endpoint representation'),
        terms_of_service='',
        contact=openapi.Contact(email=settings.YASG_DEFAULT_EMAIL),
        license=openapi.License(name=settings.YASG_TERMS_OF_SERVICE),
    ),
    public=False,
)

swagger_urls = [
    re_path(
        r'^api/docs/',
        schema_view.with_ui(
            'swagger',
            cache_timeout=0
        ),
        name='schema-swagger-ui'
    ),
    re_path(
        r'^api/redocs/',
        schema_view.with_ui(
            'redoc',
            cache_timeout=0
        ),
        name='schema-redoc'
    ),
    re_path(
        r'^api/docs/<format>/',
        schema_view.without_ui(
            cache_timeout=0
        ),
        name='schema-json-yaml'
    ),
]

ckeditor_urls = [
    path(
        "ckeditor5/",
        include('django_ckeditor_5.urls')
    ),
]

django_select2_urls = [
    path(
        'select2/',
        include('django_select2.urls')
    )
]

urlpatterns = admin_urls + two_factor_urls + \
    apps_urls + third_party_urls + swagger_urls + ckeditor_urls + django_select2_urls

if settings.DEBUG:
    urlpatterns += static(
        settings.STATIC_URL,
        document_root=settings.STATIC_ROOT
    )
    urlpatterns += static(
        settings.MEDIA_URL,
        document_root=settings.MEDIA_ROOT
    )

apps/common/core/urls.py
from django.urls import include, path

from apps.common.core.views import IndexTemplateView

app_name = 'core'

urlpatterns = [
    path(
        '',
        IndexTemplateView.as_view(),
        name='index'
    )
]

apps/project/specific/documents/certificates/urls.py
from django.urls import path

from .views import LockoutTimeView, CertificateInputView, CertificateDetailView, SovereignPurchaseCertificateDetailView, SovereignPurchaseCertificateInputView

app_name = 'certificates'

urlpatterns = [

    path(
        'lockout-time/',
        LockoutTimeView.as_view(),
        name='lockout_time'
    ),



    path(
        'certificate/',
        CertificateInputView.as_view(),
        name='input'
    ),
    path(
        'certificate/<uuid:pk>/',
        CertificateDetailView.as_view(),
        name='detail'
    ),



    path(
        'certificate/sovereign/',
        SovereignPurchaseCertificateInputView.as_view(),
        name='sovereign_input'
    ),
    path(
        'certificate/sovereign/<uuid:pk>/',
        SovereignPurchaseCertificateDetailView.as_view(),
        name='sovereign_detail'
    ),
]

apps/project/specific/internal/certificates/models.py
import hashlib
import uuid

from django.db import models
from django.utils.translation import gettext_lazy as _
from encrypted_model_fields.fields import EncryptedCharField

from apps.common.utils.models import TimeStampedModel


class CertificateModel(TimeStampedModel):
    class DocumentTypeChoices(models.TextChoices):
        CC = 'CC', _('Citizen ID (CC)')
        CE = 'CE', _('Foreigner ID (CE)')
        PPT = 'PPT', _('Special Residence Permit (PPT)')
        TI = 'TI', _('Identity Card (TI)')
        PA = 'PA', _('Passport (PA)')
        RC = 'RC', _('Civil Registry (RC)')
        NIT = 'NIT', _('Tax Identification Number (NIT)')
        RUT = 'RUT', _('Single Tax Registry (RUT)')
        CD = 'CD', _('Diplomatic ID Card (CD)')

    id = models.UUIDField(
        'ID',
        default=uuid.uuid4,
        unique=True,
        primary_key=True,
        serialize=False,
        editable=False
    )

    name = models.CharField(
        _('Name'),
        max_length=100
    )

    document_type = models.CharField(
        _('Document type'),
        max_length=4,
        choices=DocumentTypeChoices.choices,
        default=DocumentTypeChoices.CC
    )

    document_number = EncryptedCharField(
        _('Document number'),
        max_length=20,
    )

    document_number_hash = models.CharField(
        max_length=64,
        editable=False,
        default='',
    )

    step = models.IntegerField(
        _('Step'),
        default=1,
        help_text=_('Step of the certificate')
    )

    approved = models.BooleanField(
        _('Approved'),
        default=True,
    )

    def masked_document_number(self):
        """Returns the ID number with all but the last four digits masked."""
        document_number_str = str(self.document_number)
        last_four = document_number_str[-4:]
        masked = '*' * (len(document_number_str) - 4) + last_four
        return masked

    def save(self, *args, **kwargs):
        self.name = self.name.upper()
        self.document_number_hash = hashlib.sha256(
            self.document_number.encode()).hexdigest()
        super().save(*args, **kwargs)

    def __str__(self):
        return f'{self.name} {self.masked_document_number()}'

    class Meta:
        db_table = "apps_project_specific_certificates_certificate"
        verbose_name = _("Certificate")
        verbose_name_plural = _("Certificates")
        ordering = ["default_order", "-created"]
        unique_together = ['document_number', 'document_type']
        permissions = [
            ('view_certificate', 'Can view certificate list'),
        ]

apps/project/specific/documents/certificates/forms.py
import re

from django import forms
from django.utils.translation import gettext_lazy as _

from .models import CertificateModel


class IDNumberForm(forms.Form):

    document_type = forms.ChoiceField(
        label=_("Document Type"),
        choices=CertificateModel.DocumentTypeChoices.choices,
        initial=CertificateModel.DocumentTypeChoices.CC
    )

    document_number = forms.CharField(
        label=_('Document Number'),
        max_length=64
    )
    
class IDNumberMinForm(forms.Form):

    document_type = forms.ChoiceField(
        label=_("Document Type"),
        choices=CertificateModel.DocumentTypeChoicesMin.choices,
        initial=CertificateModel.DocumentTypeChoicesMin.PA
    )

    document_number = forms.CharField(
        label=_('Document Number'),
        max_length=64
    )

apps/project/specific/documents/certificates/views.py
import base64
import hashlib
import logging
from datetime import timedelta
from io import BytesIO

import barcode
import qrcode
import requests
from barcode.writer import ImageWriter
from django.contrib import messages
from django.http import JsonResponse
from django.shortcuts import redirect
from django.utils import timezone
from django.utils.safestring import mark_safe
from django.utils.translation import gettext_lazy as _
from django.views.generic import DetailView, FormView, View
from PIL import Image

from .forms import IDNumberForm, IDNumberMinForm
from .models import CertificateModel, CertificateTypesModel

logging = logging.getLogger(__name__)


def generate_qr_with_favicon(text_data: str, image_url: str = "https://atlas.propensionesabogados.com/static/assets/imgs/favicon/atlas-favicon512x512.png"):
    qr = qrcode.QRCode(
        version=1,
        error_correction=qrcode.constants.ERROR_CORRECT_H,
        box_size=10,
        border=4,
    )
    qr.add_data(text_data)
    qr.make(fit=True)
    img_qr = qr.make_image(fill="black", back_color="white").convert("RGB")

    try:
        icon_url = image_url
        response = requests.get(icon_url)
        response.raise_for_status()
        icon = Image.open(BytesIO(response.content))
        icon = icon.resize(
            (img_qr.size[0] // 4, img_qr.size[1] // 4), Image.LANCZOS)
        pos = ((img_qr.size[0] - icon.size[0]) // 2,
               (img_qr.size[1] - icon.size[1]) // 2)
        img_qr.paste(icon, pos, icon)
    except Exception as e:
        logging.error(f"Error: {e}")

    buffer = BytesIO()
    img_qr.save(buffer, format="PNG")
    qr_base64 = base64.b64encode(buffer.getvalue()).decode()

    return f"data:image/png;base64,{qr_base64}"


def generate_barcode(custom_text: str):
    buffer = BytesIO()
    barcode_class = barcode.get_barcode_class('code128')
    barcode_image = barcode_class(
        custom_text,
        writer=ImageWriter()
    )
    barcode_image.write(buffer)
    barcode_base64 = base64.b64encode(buffer.getvalue()).decode()
    return f"data:image/png;base64,{barcode_base64}"


class LockoutTimeView(View):
    def get(self, request):
        lockout_time = request.session.get('lockout_time')
        if lockout_time:
            lockout_time = timezone.make_aware(
                timezone.datetime.fromtimestamp(lockout_time))
            lockout_duration = timedelta(minutes=60)
            if timezone.now() < lockout_time + lockout_duration:
                remaining_time = (
                    lockout_time + lockout_duration - timezone.now()).seconds
                return JsonResponse({'remaining_time': remaining_time})

        return JsonResponse({'remaining_time': 0})


# Idoneity

class CertificateInputView(FormView):
    template_name = 'dashboard/pages/documents/certificates/idoneity/certificate_input.html'
    form_class = IDNumberForm

    def form_valid(self, form):
        max_attempts = 5
        lockout_duration = timedelta(minutes=60)
        failed_attempts = self.request.session.get('failed_attempts', 0)
        lockout_time = self.request.session.get('lockout_time')
        if lockout_time:
            lockout_time = timezone.make_aware(
                timezone.datetime.fromtimestamp(lockout_time))
            if timezone.now() < lockout_time + lockout_duration:
                messages.error(
                    self.request,
                    _('Too many failed attempts.')
                )
                return self.form_invalid(form)
            else:
                self.request.session['failed_attempts'] = 0
                self.request.session['lockout_time'] = None

        document_type = form.cleaned_data['document_type']
        document_number = form.cleaned_data['document_number'].strip().upper()
        document_number_hash = hashlib.sha256(
            document_number.encode()).hexdigest()

        try:
            certificate = CertificateModel.objects.get(
                document_type=document_type,
                document_number_hash=document_number_hash,
                certificate_type=CertificateTypesModel.objects.get(
                    name=CertificateTypesModel.CertificateTypeChoices.IDONEITY
                )
            )
            self.request.session['failed_attempts'] = 0
            self.request.session['lockout_time'] = None
            return redirect('certificates:detail', pk=certificate.id)

        except CertificateModel.DoesNotExist:
            failed_attempts += 1
            self.request.session['failed_attempts'] = failed_attempts
            if failed_attempts >= max_attempts:
                self.request.session['lockout_time'] = timezone.now(
                ).timestamp()
                messages.error(
                    self.request, _(
                        'Too many failed attempts.'
                    )
                )
            else:
                form.add_error('document_number', _('ID Number not found.'))
            return self.form_invalid(form)


class CertificateDetailView(DetailView):
    model = CertificateModel
    template_name = 'dashboard/pages/documents/certificates/idoneity/certificate_detail.html'
    context_object_name = 'certificate'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        custom_text = "atlas.propensionesabogados.com/certificate/{}".format(
            str(self.object.pk)
        )

        certificate_url = "https://atlas.propensionesabogados.com/certificate/{}".format(
            self.object.pk
        )

        context['qr_code'] = mark_safe(
            generate_qr_with_favicon(certificate_url)
        )

        context['barcode'] = mark_safe(
            generate_barcode(custom_text)
        )

        return context


# Sovereign Purchase

class SovereignPurchaseCertificateInputView(FormView):
    template_name = 'dashboard/pages/documents/certificates/sovereing/certificate_input.html'
    form_class = IDNumberMinForm

    def form_valid(self, form):
        max_attempts = 5
        lockout_duration = timedelta(minutes=60)
        failed_attempts = self.request.session.get('failed_attempts', 0)
        lockout_time = self.request.session.get('lockout_time')
        if lockout_time:
            lockout_time = timezone.make_aware(
                timezone.datetime.fromtimestamp(lockout_time))
            if timezone.now() < lockout_time + lockout_duration:
                messages.error(
                    self.request,
                    _('Too many failed attempts.')
                )
                return self.form_invalid(form)
            else:
                self.request.session['failed_attempts'] = 0
                self.request.session['lockout_time'] = None

        document_type = form.cleaned_data['document_type']
        document_number = form.cleaned_data['document_number'].strip().upper()
        document_number_hash = hashlib.sha256(
            document_number.encode()).hexdigest()

        try:
            certificate = CertificateModel.objects.get(
                document_type=document_type,
                document_number_hash=document_number_hash,
                certificate_type=CertificateTypesModel.objects.get(
                    name=CertificateTypesModel.CertificateTypeChoices.SOVEREIGN_PURCHASE)
            )
            self.request.session['failed_attempts'] = 0
            self.request.session['lockout_time'] = None
            return redirect('certificates:sovereign_detail', pk=certificate.id)

        except CertificateModel.DoesNotExist:
            failed_attempts += 1
            self.request.session['failed_attempts'] = failed_attempts
            if failed_attempts >= max_attempts:
                self.request.session['lockout_time'] = timezone.now(
                ).timestamp()
                messages.error(
                    self.request, _(
                        'Too many failed attempts.'
                    )
                )
            else:
                form.add_error('document_number', _('ID Number not found.'))
            return self.form_invalid(form)


class SovereignPurchaseCertificateDetailView(DetailView):
    model = CertificateModel
    template_name = 'dashboard/pages/documents/certificates/sovereing/certificate_detail.html'
    context_object_name = 'certificate'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        custom_text = "atlas.propensionesabogados.com/certificate/sovereing/{}".format(
            str(self.object.pk)
        )

        certificate_url = "https://atlas.propensionesabogados.com/certificate/sovereing/{}".format(
            self.object.pk
        )

        context['qr_code'] = mark_safe(
            generate_qr_with_favicon(certificate_url)
        )

        context['barcode'] = mark_safe(
            generate_barcode(custom_text)
        )

        return context

templates/dashboard/pages/documents/certificates/idoneity/certificate_detail.html
{% extends 'dashboard/pages/documents/certificates/certificate_base.html' %}

{% load static i18n %}

{% block title %}{% trans 'Certificate Details' %}{% endblock title %}

{% block main %}
<div class="container mt-5 min-vh-100">
    <div class="mx-auto">
        <div class="text-center mb-4">
            <h1>{% trans 'Suitability Verification' %}</h1>
        </div>
        <div class="row">
            <div class="col-md-4 text-center">
                <div class="row text-center">
                    <div class="col-sm-6 col-md-12 text-center">
                        <img src="{% static 'assets/imgs/suitability/certificate_badge.png' %}" alt="Certificate Badge" class="mb-4" style="max-width: 150px;">
                    </div>
                    <div class="col-sm-6 col-md-12">
                        <img id="qr-code" src="{{ qr_code }}" alt="QR Code" class="img-fluid" style="max-width: 150px;">
                    </div>
                </div>
            </div>

            <div class="col-md-8">
                <div>
                    <h2>{{ certificate.name }} {{ certificate.last_name }}</h2>
                    <p class="mb-1"><strong>{% trans 'ID Number:' %}</strong> {{ certificate.masked_document_number }}</p>
                    <p class="mb-1"><strong>{% trans 'Certificate ID:' %}</strong> {{ certificate.id }}</p>
                    {% if certificate.approved %}
                        <h3 class="text-success">{% trans 'Approved' %}</h3>
                    {% else %}
                        <h3 class="text-danger">{% trans 'Not Approved' %}</h3>
                    {% endif %}
                    <hr>
                    {% if certificate.approved %}
                        <p class="text-justify">
                                <strong>{{ certificate.name }} {{ certificate.last_name }}</strong>
                                {% trans 'with document number' %} {{ certificate.document_type }} {{ certificate.masked_document_number }}
                                {% blocktrans %}
                                qualifies as a beneficiary, who has undergone a security screening and accreditation of judicial records in accordance with current regulations, criminal reports on social media, and Interpol databases. Consequently, they do <strong>NOT</strong> have any judicial or disciplinary records from the certifying entities authorized by international public consultation databases, which would affect their suitability.
                                <br/>
                                For the record, this is signed on {% endblocktrans %} {{ certificate.approval_date|date:"d/m/Y" }} {% trans 'in Quindío, Republic of Colombia.' %}
                        </p>
                    {% else %}
                        <p class="text-justify">
                            <strong>{{ certificate.name }} {{ certificate.last_name }}</strong>
                            {% trans 'with document number' %} {{ certificate.document_type }} {{ certificate.masked_document_number }}
                            {% blocktrans %}
                                we inform you that, after the evaluation conducted, your security study <span class="text-danger">HAS NOT BEEN APPROVED</span> due to not meeting the suitability requirements according to the current security regulations.
                            {% endblocktrans %}
                        </p>
                    {% endif %}
                    <p>
                        <small>
                            {% trans 'We remind you that, in accordance with the provisions of the Habeas Data Law, all your personal data has been treated with due confidentiality and is protected under the strictest security standards, guaranteeing its integrity and privacy. Your data will be used exclusively for authorized purposes and within the framework of current data protection regulations.' %}
                        </small>
                    </p>
                    <p>
                        {% trans 'Status:' %}
                        {% if certificate.approved %}
                            <i class="bi bi-check-circle text-success"></i>
                        {% else %}
                            <i class="bi bi-x-circle text-danger"></i>
                        {% endif %}
                    </p>
                    <div class="text-center">
                        <img id="barcode" src="{{ barcode }}" alt="Barcode" style="max-width: 100%;">
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock main %}

templates/dashboard/pages/documents/certificates/idoneity/certificate_input.html
{% extends 'dashboard/pages/documents/certificates/certificate_base.html' %}

{% load static i18n %}

{% block title %}{% trans 'Verify your Certificate' %}{% endblock title %}

{% block main %}
<div class="container mt-5">
    <div class="container text-center">
        <a href="{% url 'core:index' %}">
            <img src="{% static 'assets/imgs/horizontal-logo.png' %}" alt="" class="img-fluid" style="max-height: 140px;"/>
        </a>
    </div>
    <h1 class="mb-4 text-center">{% trans 'Verify your Certificate' %}</h1>
    <form method="post" novalidate>
        {% csrf_token %}
        <div class="row justify-content-center">
            <div class="col-md-6">
                {{ form.non_field_errors }}
                <div class="form-floating mb-3">
                    <select name="{{ form.document_type.name }}"
                            id="floatingDocumentType"
                            class="form-select{% if form.document_type.errors %} is-invalid{% endif %}">
                        {% for choice in form.document_type.field.choices %}
                            <option value="{{ choice.0 }}"{% if choice.0 == form.document_type.value %}selected{% endif %}>
                                {{ choice.1 }}
                            </option>
                        {% endfor %}
                    </select>
                    <label for="floatingDocumentType">{{ form.document_type.label }}</label>
                    {% if form.document_type.errors %}
                        <div class="invalid-feedback">
                            {{ form.document_type.errors.as_text }}
                        </div>
                    {% endif %}
                </div>
                <div class="form-floating mb-3">
                    <input type="text"
                           name="{{ form.document_number.name }}"
                           id="floatingIDNumber"
                           class="form-control{% if form.document_number.errors %} is-invalid{% endif %}"
                           placeholder="C.C."
                           value="{{ form.document_number.value|default_if_none:'' }}">
                    <label for="floatingIDNumber">{{ form.document_number.label }}</label>
                    {% if form.document_number.errors %}
                        <div class="invalid-feedback">
                            {{ form.document_number.errors.as_text }}
                        </div>
                    {% endif %}
                </div>
                
                {% if messages %}
                    <div class="alert alert-danger" role="alert">
                        {% for message in messages %}
                        <div id="lockout-timer">
                            <p id="remaining-time">{{ message }} {% trans 'Please try again in' %} <span id="time-left">0</span> {% trans 'minutes.' %}</p>
                        </div>
                        {% endfor %}
                    </div>
                {% endif %}
                
            <button type="submit" class="btn btn-primary w-100">{% trans 'Verify' %}</button>
            </div>
        </div>
        
    </form>
</div>
{% endblock main %}


{% block body_custom_js %}
<script>
    function updateRemainingTime() {
        fetch("{% url 'certificates:lockout_time' %}")
            .then(response => response.json())
            .then(data => {
                const remainingTime = data.remaining_time;
                if (remainingTime > 0) {
                    const minutes = Math.floor(remainingTime / 60);
                    const seconds = remainingTime % 60;
                    document.getElementById('time-left').innerText = `${minutes}:${seconds < 10 ? '0' + seconds : seconds}`;
                    document.getElementById('lockout-timer').style.display = 'block';
                } else {
                    document.getElementById('lockout-timer').style.display = 'none';
                }
            })
            .catch(error => console.error('Error fetching lockout time:', error));
    }

    document.addEventListener('DOMContentLoaded', function() {
        updateRemainingTime();
        setInterval(updateRemainingTime, 10*1000);
    });
</script>
{% endblock body_custom_js %}
    