app_core/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path, re_path
from django.utils.translation import gettext_lazy as _
from drf_yasg import openapi
from drf_yasg.views import get_schema_view
from two_factor.urls import urlpatterns as tf_urls

from apps.common.utils.views import handler400 as h400
from apps.common.utils.views import handler403 as h403
from apps.common.utils.views import handler404 as h404
from apps.common.utils.views import handler500 as h500

admin_url = settings.ADMIN_URL
custom_apps = settings.ALL_CUSTOM_APPS
utils_path = settings.UTILS_PATH

apps_urls = [path('', include(f'{app}.urls')) for app in custom_apps]

handler400 = h400

handler403 = h403

handler404 = h404

handler500 = h500

third_party_urls = [
    re_path(
        r'^rosetta/',
        include('rosetta.urls')
    ),
]

admin_urls = [
    path(admin_url, admin.site.urls),
]

two_factor_urls = [
    path('', include(tf_urls)),
]

rest_urls = [
    path(
        'api-auth/',
        include('rest_framework.urls')
    )
]

schema_view = get_schema_view(
    openapi.Info(
        title='Backend Endpoints',
        default_version='v1.0.0',
        description=_('API documentation and endpoint representation'),
        terms_of_service='',
        contact=openapi.Contact(email=settings.YASG_DEFAULT_EMAIL),
        license=openapi.License(name=settings.YASG_TERMS_OF_SERVICE),
    ),
    public=False,
)

swagger_urls = [
    re_path(
        r'^api/docs/',
        schema_view.with_ui(
            'swagger',
            cache_timeout=0
        ),
        name='schema-swagger-ui'
    ),
    re_path(
        r'^api/redocs/',
        schema_view.with_ui(
            'redoc',
            cache_timeout=0
        ),
        name='schema-redoc'
    ),
    re_path(
        r'^api/docs/<format>/',
        schema_view.without_ui(
            cache_timeout=0
        ),
        name='schema-json-yaml'
    ),
]

ckeditor_urls = [
    path(
        "ckeditor5/",
        include('django_ckeditor_5.urls')
    ),
]

django_select2_urls = [
    path(
        'select2/',
        include('django_select2.urls')
    )
]

urlpatterns = admin_urls + two_factor_urls + \
    apps_urls + third_party_urls + swagger_urls + ckeditor_urls + django_select2_urls

if settings.DEBUG:
    urlpatterns += static(
        settings.STATIC_URL,
        document_root=settings.STATIC_ROOT
    )
    urlpatterns += static(
        settings.MEDIA_URL,
        document_root=settings.MEDIA_ROOT
    )

apps/project/specific/documents/kyc/urls.py
from django.urls import path
from . import views  # Asegúrate de tener al menos una vista
app_name= 'kyc'
urlpatterns = [
    path('', views.index, name='index'),  # Esta es una URL de ejemplo
]

apps/project/specific/documents/pol/urls.py
from django.urls import path

from .views import ProofOfLifeCreateView, ProofOfLifeSuccessView

app_name = 'pol'

urlpatterns = [
    path(
        'pol/create/',
        ProofOfLifeCreateView.as_view(),
        name='create'
    ),

    path(
        'pol/success/',
        ProofOfLifeSuccessView.as_view(),
        name='success'
    ),
]

apps/project/specific/internal/code_gen/urls.py
from django.urls import path

from .views import CodeGeneratorView, dynamic_qr_view

app_name = "code_gen"

urlpatterns = [
    path(
        "generate/code/",
        CodeGeneratorView.as_view(),
        name="code_generate"
    ),
    path(
        "qr/generate/<path:text>/",
        dynamic_qr_view,
        name="dynamic_qr"
    ),
]

apps/project/specific/internal/code_gen/models.py
from django.db import models
from django.utils.translation import gettext_lazy as _

from apps.common.utils.models import TimeStampedModel


class CodeRegistrationModel(TimeStampedModel):
    reference = models.CharField(
        _('Reference'),
        max_length=100,
    )

    description = models.TextField(
        _('Description'),
        blank=True,
        null=True,
    )

    custom_text_input = models.CharField(
        _('Custom Text Input'),
        max_length=100,
        blank=True,
        null=True,
    )

    code_information = models.TextField(
        _('Code Information'),
        blank=True,
        null=True,
    )

    def __str__(self) -> str:
        return self.reference

    def save(self, *args, **kwargs):
        self.reference = self.reference.upper()
        super().save(*args, **kwargs)

    class Meta:
        db_table = 'apps_code_gen_coderegistration'
        verbose_name = _('Code Registration')
        verbose_name_plural = _('Code Registrations')

apps/project/specific/documents/certificates/forms.py
import re

from django import forms
from django.utils.translation import gettext_lazy as _

from .models import CertificateModel


class IDNumberForm(forms.Form):

    document_type = forms.ChoiceField(
        label=_("Document Type"),
        choices=CertificateModel.DocumentTypeChoices.choices,
        initial=CertificateModel.DocumentTypeChoices.CC
    )

    document_number = forms.CharField(
        label=_('Document Number'),
        max_length=64
    )
    
class IDNumberMinForm(forms.Form):

    document_type = forms.ChoiceField(
        label=_("Document Type"),
        choices=CertificateModel.DocumentTypeChoicesMin.choices,
        initial=CertificateModel.DocumentTypeChoicesMin.PA
    )

    document_number = forms.CharField(
        label=_('Document Number'),
        max_length=64
    )

apps/project/specific/internal/code_gen/forms.py
from django import forms
from django.utils.translation import gettext_lazy as _
from .models import CodeRegistrationModel


class CodeForm(forms.ModelForm):
    include_nit = forms.BooleanField(
        label=_("Include NIT"),
        required=False
    )
    include_date = forms.BooleanField(
        label=_("Include Date (DDMMYYYY)"),
        required=False
    )
    include_random_code = forms.BooleanField(
        label=_("Include Random Code (4 digits)"),
        required=False
    )
    generate_qr_code = forms.BooleanField(
        label=_("Generate QR Code"),
        required=False
    )
    qr_image_url = forms.URLField(
        label=_("QR Image URL"),
        required=False,
        widget=forms.URLInput(
            attrs={
                'class': 'form-control',
                'placeholder': _('QR Image URL')
            }
        )
    )
    generate_barcode = forms.BooleanField(
        label=_("Generate Barcode"),
        required=False
    )

    class Meta:
        model = CodeRegistrationModel
        fields = [
            'reference',
            'description',
            'custom_text_input'
        ]
        widgets = {
            'reference': forms.TextInput(
                attrs={
                    'class': 'form-control',
                    'placeholder': _('Reference'),
                    'required': True
                }
            ),
            'description': forms.Textarea(
                attrs={
                    'class': 'form-control',
                    'placeholder': _('Description')
                }
            ),
            'custom_text_input': forms.TextInput(
                attrs={
                    'class': 'form-control',
                    'placeholder': _('Custom Text'),
                    'required': True
                }
            )
        }

apps/project/specific/documents/certificates/views.py
import base64
import hashlib
import logging
from datetime import timedelta
from io import BytesIO

import barcode
import qrcode
import requests
from barcode.writer import ImageWriter
from django.contrib import messages
from django.http import JsonResponse
from django.shortcuts import redirect
from django.utils import timezone
from django.utils.safestring import mark_safe
from django.utils.translation import gettext_lazy as _
from django.views.generic import DetailView, FormView, View
from PIL import Image

from .forms import IDNumberForm, IDNumberMinForm
from .models import CertificateModel, CertificateTypesModel

logging = logging.getLogger(__name__)


def generate_qr_with_favicon(text_data: str, image_url: str = "https://atlas.propensionesabogados.com/static/assets/imgs/favicon/atlas-favicon512x512.png"):
    qr = qrcode.QRCode(
        version=1,
        error_correction=qrcode.constants.ERROR_CORRECT_H,
        box_size=10,
        border=4,
    )
    qr.add_data(text_data)
    qr.make(fit=True)
    img_qr = qr.make_image(fill="black", back_color="white").convert("RGB")

    try:
        icon_url = image_url
        response = requests.get(icon_url)
        response.raise_for_status()
        icon = Image.open(BytesIO(response.content))
        icon = icon.resize(
            (img_qr.size[0] // 4, img_qr.size[1] // 4), Image.LANCZOS)
        pos = ((img_qr.size[0] - icon.size[0]) // 2,
               (img_qr.size[1] - icon.size[1]) // 2)
        img_qr.paste(icon, pos, icon)
    except Exception as e:
        logging.error(f"Error: {e}")

    buffer = BytesIO()
    img_qr.save(buffer, format="PNG")
    qr_base64 = base64.b64encode(buffer.getvalue()).decode()

    return f"data:image/png;base64,{qr_base64}"


def generate_barcode(custom_text: str):
    buffer = BytesIO()
    barcode_class = barcode.get_barcode_class('code128')
    barcode_image = barcode_class(
        custom_text,
        writer=ImageWriter()
    )
    barcode_image.write(buffer)
    barcode_base64 = base64.b64encode(buffer.getvalue()).decode()
    return f"data:image/png;base64,{barcode_base64}"


class LockoutTimeView(View):
    def get(self, request):
        lockout_time = request.session.get('lockout_time')
        if lockout_time:
            lockout_time = timezone.make_aware(
                timezone.datetime.fromtimestamp(lockout_time))
            lockout_duration = timedelta(minutes=60)
            if timezone.now() < lockout_time + lockout_duration:
                remaining_time = (
                    lockout_time + lockout_duration - timezone.now()).seconds
                return JsonResponse({'remaining_time': remaining_time})

        return JsonResponse({'remaining_time': 0})


# Idoneity

class CertificateInputView(FormView):
    template_name = 'dashboard/pages/documents/certificates/idoneity/certificate_input.html'
    form_class = IDNumberForm

    def form_valid(self, form):
        max_attempts = 5
        lockout_duration = timedelta(minutes=60)
        failed_attempts = self.request.session.get('failed_attempts', 0)
        lockout_time = self.request.session.get('lockout_time')
        if lockout_time:
            lockout_time = timezone.make_aware(
                timezone.datetime.fromtimestamp(lockout_time))
            if timezone.now() < lockout_time + lockout_duration:
                messages.error(
                    self.request,
                    _('Too many failed attempts.')
                )
                return self.form_invalid(form)
            else:
                self.request.session['failed_attempts'] = 0
                self.request.session['lockout_time'] = None

        document_type = form.cleaned_data['document_type']
        document_number = form.cleaned_data['document_number'].strip().upper()
        document_number_hash = hashlib.sha256(
            document_number.encode()).hexdigest()

        try:
            certificate = CertificateModel.objects.get(
                document_type=document_type,
                document_number_hash=document_number_hash,
                certificate_type=CertificateTypesModel.objects.get(
                    name=CertificateTypesModel.CertificateTypeChoices.IDONEITY
                )
            )
            self.request.session['failed_attempts'] = 0
            self.request.session['lockout_time'] = None
            return redirect('certificates:detail', pk=certificate.id)

        except CertificateModel.DoesNotExist:
            failed_attempts += 1
            self.request.session['failed_attempts'] = failed_attempts
            if failed_attempts >= max_attempts:
                self.request.session['lockout_time'] = timezone.now(
                ).timestamp()
                messages.error(
                    self.request, _(
                        'Too many failed attempts.'
                    )
                )
            else:
                form.add_error('document_number', _('ID Number not found.'))
            return self.form_invalid(form)


class CertificateDetailView(DetailView):
    model = CertificateModel
    template_name = 'dashboard/pages/documents/certificates/idoneity/certificate_detail.html'
    context_object_name = 'certificate'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        custom_text = "atlas.propensionesabogados.com/certificate/{}".format(
            str(self.object.pk)
        )

        certificate_url = "https://atlas.propensionesabogados.com/certificate/{}".format(
            self.object.pk
        )

        context['qr_code'] = mark_safe(
            generate_qr_with_favicon(certificate_url)
        )

        context['barcode'] = mark_safe(
            generate_barcode(custom_text)
        )

        return context


# Sovereign Purchase

class SovereignPurchaseCertificateInputView(FormView):
    template_name = 'dashboard/pages/documents/certificates/sovereing/certificate_input.html'
    form_class = IDNumberMinForm

    def form_valid(self, form):
        max_attempts = 5
        lockout_duration = timedelta(minutes=60)
        failed_attempts = self.request.session.get('failed_attempts', 0)
        lockout_time = self.request.session.get('lockout_time')
        if lockout_time:
            lockout_time = timezone.make_aware(
                timezone.datetime.fromtimestamp(lockout_time))
            if timezone.now() < lockout_time + lockout_duration:
                messages.error(
                    self.request,
                    _('Too many failed attempts.')
                )
                return self.form_invalid(form)
            else:
                self.request.session['failed_attempts'] = 0
                self.request.session['lockout_time'] = None

        document_type = form.cleaned_data['document_type']
        document_number = form.cleaned_data['document_number'].strip().upper()
        document_number_hash = hashlib.sha256(
            document_number.encode()).hexdigest()

        try:
            certificate = CertificateModel.objects.get(
                document_type=document_type,
                document_number_hash=document_number_hash,
                certificate_type=CertificateTypesModel.objects.get(
                    name=CertificateTypesModel.CertificateTypeChoices.SOVEREIGN_PURCHASE)
            )
            self.request.session['failed_attempts'] = 0
            self.request.session['lockout_time'] = None
            return redirect('certificates:sovereign_detail', pk=certificate.id)

        except CertificateModel.DoesNotExist:
            failed_attempts += 1
            self.request.session['failed_attempts'] = failed_attempts
            if failed_attempts >= max_attempts:
                self.request.session['lockout_time'] = timezone.now(
                ).timestamp()
                messages.error(
                    self.request, _(
                        'Too many failed attempts.'
                    )
                )
            else:
                form.add_error('document_number', _('ID Number not found.'))
            return self.form_invalid(form)


class SovereignPurchaseCertificateDetailView(DetailView):
    model = CertificateModel
    template_name = 'dashboard/pages/documents/certificates/sovereing/certificate_detail.html'
    context_object_name = 'certificate'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        custom_text = "atlas.propensionesabogados.com/certificate/sovereing/{}".format(
            str(self.object.pk)
        )

        certificate_url = "https://atlas.propensionesabogados.com/certificate/sovereing/{}".format(
            self.object.pk
        )

        context['qr_code'] = mark_safe(
            generate_qr_with_favicon(certificate_url)
        )

        context['barcode'] = mark_safe(
            generate_barcode(custom_text)
        )

        return context

apps/project/specific/documents/kyc/views.py
from django.shortcuts import render

# Create your views here.
# apps/project/specific/documents/kyc/views.py

from django.http import HttpResponse

def index(request):
    return HttpResponse("Página de inicio de KYC")

apps/project/specific/documents/pol/views.py
from django.urls import reverse_lazy
from django.views.generic import CreateView, TemplateView

from .forms import ProofOfLifeForm
from .models import ProofOfLifeModel


class ProofOfLifeCreateView(CreateView):
    """
    Vista basada en clases (CBV) que crea un registro de prueba de vida (POL).
    """
    model = ProofOfLifeModel
    form_class = ProofOfLifeForm
    template_name = "dashboard/pages/documents/pol/pol_form.html"
    success_url = reverse_lazy("pol:success")

    def form_valid(self, form):
        return super().form_valid(form)


class ProofOfLifeSuccessView(TemplateView):
    """
    Vista mostrada al completar exitosamente la prueba de vida.
    """
    template_name = "dashboard/pages/documents/pol/pol_success.html"

templates/dashboard/pages/documents/code_gen/code_form.html
{% extends 'core/base.html' %}

{% load i18n static %}

{% block title %}
    {% trans 'Code Generator' %}
{% endblock title %}

{% block meta %}
<meta charset="UTF-8">
<meta content="text/html; charset=utf-8" http-equiv="Content-Type" />
<meta content="width=device-width, initial-scale=1.0" name="viewport"/>

<meta content="noindex, nofollow, noarchive" name="robots"  />
<meta content="noindex, nofollow, noarchive" name="googlebot" />
{% endblock meta %}

{% block third_css %}
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons/font/bootstrap-icons.css" rel="stylesheet">
{% endblock third_css %}

{% block custom_css %}
    <link href="{% static 'assets/css/site/main.css' %}" rel="stylesheet">
{% endblock custom_css %}

{% block header %}
    {% include 'core/partials/header.html' %}
{% endblock header %}

{% block main %}
    <main class="container min-vh-100" style="padding-top: 100px;">
        <h1 class="my-4 text-center">{% trans 'Code Generator' %}</h1>
        <form id="barcodeForm" method="post">
            {% csrf_token %}

            <div class="form-floating mb-3">
                <input type="text" class="form-control" id="id_reference" placeholder="{% trans 'Reference' %}" name="id_reference" required>
                <label for="id_reference">{% trans 'Reference' %}*</label>
            </div>

            <div class="form-floating mb-3">
                <textarea type="text" class="form-control" id="id_description" placeholder="{% trans 'Reference' %}" name="id_description" style="height: 100px"></textarea>
                <label for="id_description">{% trans 'Description' %}</label>
            </div>

            <div class="form-floating mb-3">
                <input type="text" class="form-control" id="id_custom_text_input" placeholder="{% trans 'Custom Text' %}" name="id_custom_text_input" required>
                <label for="id_custom_text_input">{% trans 'Custom Text' %}*</label>
            </div>

            <div class="row g-2">
                <div class="col-md">
                    <div class="form-check mb-3">
                        <input class="form-check-input" type="checkbox" id="id_include_nit">
                        <label class="form-check-label" for="id_include_nit">{% trans 'Include NIT' %}</label>
                    </div>
                </div>
                <div class="col-md">
                    <div class="form-check mb-3">
                        <input class="form-check-input" type="checkbox" id="id_include_date">
                        <label class="form-check-label" for="id_include_date">{% trans 'Include Date (DDMMYYYY)' %}</label>
                    </div>
                </div>
                <div class="col-md">
                    <div class="form-check mb-3">
                        <input class="form-check-input" type="checkbox" id="id_include_random_code">
                        <label class="form-check-label" for="id_include_random_code">{% trans 'Include Random Code (4 digits)' %}</label>
                    </div>
                </div>
                <div class="col-md">
                    <div class="form-check mb-3">
                        <input class="form-check-input" type="checkbox" id="id_generate_barcode">
                        <label class="form-check-label" for="id_generate_barcode">{% trans 'Generate Barcode' %}</label>
                    </div>
                </div>
                <div class="col-md">
                    <div class="form-check mb-3">
                        <input class="form-check-input" type="checkbox" id="id_generate_qr_code">
                        <label class="form-check-label" for="id_generate_qr_code">{% trans 'QR Code' %}</label>
                    </div>
                </div>
            </div>



            <div class="d-grid gap-2">
                <button type="button" id="generateBarcode" class="btn btn-primary">{% trans 'Next' %} <i class="bi bi-upc-scan"></i></button>
            </div>

        </form>

        <div id="barcodeOutput" class="mt-2 mb-2 text-center" style="display:none;">
            <div class="d-grid gap-2">
                <a id="downloadLink" download class="btn btn-success mt-3">{% trans 'Download' %} <i class="bi bi-cloud-arrow-down"></i></a>
            </div>
            <img id="barcodeImage" class="img-fluid" src="{{ barcode_image }}" alt="{% trans 'Bar Code' %}"/>
        </div>

        <div id="qrOutput" class="mt-2 mb-2 text-center" style="display:none;">
            <div class="d-grid gap-2">
                <a id="downloadQRLink" download class="btn btn-success mt-3">
                    {% trans 'Download QR' %} <i class="bi bi-cloud-arrow-down"></i>
                </a>
            </div>
            <img id="qrImage" class="img-fluid" src="" alt="{% trans 'QR Code' %}" />
            <div class="mt-2">
                <a id="qrTextLink" href="" target="_blank"></a>
            </div>
            <div class="mt-2">
                <p id="qrDynamicUrl"></p>
            </div>
        </div>
        
        
    </main>
{% endblock main %}

{% block body_custom_js %}
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <script>
        $(document).ready(function () {
            const csrftoken = document.querySelector('[name=csrfmiddlewaretoken]').value;
        
            $("#generateBarcode").click(function () {
                const isValid = validateForm();

                if (!isValid) {
                    alert("Por favor, completa todos los campos requeridos.");
                    return;
                }

                const reference = $("#id_reference").val();
                const description = $("#id_description").val();
                const customTextInput = $("#id_custom_text_input").val();
                const includeNIT = $("#id_include_nit").is(":checked");
                const includeDate = $("#id_include_date").is(":checked");
                const includeRandomCode = $("#id_include_random_code").is(":checked");
                const generateQRCode = $("#id_generate_qr_code").is(":checked");
                const generateBarcode = $("#id_generate_barcode").is(":checked");
                
                $.ajax({
                    url: "{% url 'code_gen:code_generate' %}",
                    type: "POST",
                    headers: {
                        "X-CSRFToken": csrftoken,
                    },
                    data: {
                        reference: reference,
                        description: description,
                        custom_text_input: customTextInput,
                        include_nit: includeNIT,
                        include_date: includeDate,
                        include_random_code: includeRandomCode,
                        generate_qr_code: generateQRCode,
                        generate_barcode: generateBarcode  // Nuevo dato
                    },
                    success: function (response) {
                        if (response.barcode_image) {
                            $("#barcodeOutput").show();
                            const imageUrl = response.barcode_image;
                            $("#barcodeImage").attr("src", imageUrl);
                            $("#downloadLink").attr("href", imageUrl);
                        }
                
                        if (response.qr_image_url) {
                            $("#qrOutput").show();
                            const qrImageUrl = response.qr_image_url;
                            $("#qrImage").attr("src", qrImageUrl);
                            $("#downloadQRLink").attr("href", qrImageUrl);
                        
                            const dynamicUrl = response.qr_image_url;
                            $("#qrDynamicUrl").text(dynamicUrl).wrap(`<a href="${dynamicUrl}" target="_blank"></a>`);
                        }
                    },
                    error: function (xhr) {
                        alert(xhr.responseJSON.error);
                    }
                });
            
            
            });
        
            // Función para validar los campos del formulario
            function validateForm() {
                let isValid = true;
        
                // Campos requeridos
                if ($("#id_reference").val().trim() === "") {
                    $("#id_reference").addClass("is-invalid");
                    isValid = false;
                } else {
                    $("#id_reference").removeClass("is-invalid");
                }
        
                if ($("#id_custom_text_input").val().trim() === "") {
                    $("#id_custom_text_input").addClass("is-invalid");
                    isValid = false;
                } else {
                    $("#id_custom_text_input").removeClass("is-invalid");
                }
        
                return isValid;
            }
        });
    </script>
    <script src="{% static 'assets/js/site/main.js' %}"></script>
{% endblock body_custom_js %}

{% block footer %}
    {% include 'core/partials/footer.html' %}
{% endblock footer %}